### ISSUE TITLE
Billing code.

### ISSUE THREAD

**Issue by adrianmkng** [iagcl/watchmen#10]
Hey guys, you have `billing_code` details set in yaml files in the `watchmen_cloudformation` still.

**Comment by adrianmkng** [comment]
PR #11 opened.

**Comment by shrutikembhavi** [comment]
Hi @adrianmkng Thanks for raising this issue. We will review your PR shortly.

**Comment by shrutikembhavi** [comment]
@adrianmkng We have reviewed your PR, and merged it :) Thanks ! Please advise if the issue can be closed.

**Comment by shrutikembhavi** [comment]
Issue resolved.
