### ISSUE TITLE
Error deploying Watchmen

### ISSUE THREAD

**Issue by adrianmkng** [iagcl/watchmen#9]
I'm trying to deploy Watchmen as per the instructions, but I'm getting this warning and this error:

```
/usr/lib/python2.7/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
fatal error: An error occurred (NoSuchBucket) when calling the ListObjects operation: The specified bucket does not exist
make: *** [create-zips] Error 1
Makefile:77: recipe for target 'deploy-watchmen-core-in-docker' failed
make: *** [deploy-watchmen-core-in-docker] Error 2
```

I was under the impression that Watchmen would create the buckets for me, is this not correct? Also I'm not sure which bucket it's expecting to be there.

**Comment by shrutikembhavi** [comment]
Hi @adrianmkng , So you need to specify an existing S3 "Bucket name" for watchmen deployment. Apologies if this is not clear from the deployment documentation.
Please deploy with a bucket name, and advise if the issue can be resolved.

**Comment by adrianmkng** [comment]
Thanks @shrutikembhavi, I'll close this ticket for now. I might try and create a PR that will create the buckets as part of watchmen.
